package ge.lilchacha.entity.enums;

public enum UserView {
    REGISTER_VIEW,
    HOME_MENU_VIEW,
    PROFILE_VIEW_HOME,
    PROFILE_VIEW_ADD_NEW,
    PAYMENT_VIEW,
    GDZ_CALL_VIEW_INCALL,
    GDZ_CALL_VIEW_OUTCALL,
    GPT_CALL_VIEW_INCALL,
    GPT_CALL_VIEW_OUTCALL,
    ACTIVATION_VIEW_1,
    ACTIVATION_VIEW_2,
    HELP_VIEW;
}
